/* tslint:disable */
/* eslint-disable */
/**
 * System rezerwacji miejsc na eventy
 * Niniejsza dokumentacja stanowi opis REST API implemtowanego przez serwer centralny. Endpointy 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: XXX@pw.edu.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Category } from './category';
import { EventStatus } from './event-status';
/**
 * 
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * 
     * @type {number}
     * @memberof Event
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Event
     */
    freePlace?: number;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof Event
     */
    startTime?: number;
    /**
     * 
     * @type {number}
     * @memberof Event
     */
    endTime?: number;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    placeSchema?: string;
    /**
     * 
     * @type {EventStatus}
     * @memberof Event
     */
    status?: EventStatus;
    /**
     * 
     * @type {Array<Category>}
     * @memberof Event
     */
    categories?: Array<Category>;
}
