/* tslint:disable */
/* eslint-disable */
/**
 * System rezerwacji miejsc na eventy
 * Niniejsza dokumentacja stanowi opis REST API implemtowanego przez serwer centralny. Endpointy 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: XXX@pw.edu.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ReservationDTO
 */
export interface ReservationDTO {
    /**
     * 
     * @type {number}
     * @memberof ReservationDTO
     */
    eventId?: number;
    /**
     * 
     * @type {number}
     * @memberof ReservationDTO
     */
    placeId?: number;
    /**
     * 
     * @type {string}
     * @memberof ReservationDTO
     */
    reservationToken?: string;
}
